language: node_js
node_js:
- '11'
after_success:
- chmod +x ".travis/public-deploy.sh"
- ".travis/public-deploy.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_cc276da88a52_key -iv $encrypted_cc276da88a52_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
